nohup python3.7 ftx-btc.py &
nohup python3.7 ftx-eth.py &
nohup python3.7 ftx-eos.py &
nohup python3.7 ftx-ltc.py &
nohup python3.7 ftx-bsv.py &
nohup python3.7 ftx-alt.py &
nohup python3.7 ftx-shit.py &
nohup python3.7 ftx-bch.py &
nohup python3.7 ftx-xtz.py &
nohup python3.7 ftx-xrp.py &
